# ---
# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   namespace: crossplane-system
#   name: provider-azure-management
# spec:
#   package: xpkg.upbound.io/upbound/provider-azure-management:v0.42.1
# ---
# apiVersion: azure.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   namespace: crossplane-system
#   name: default
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: azure-secret
#       key: creds
# ---

# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   namespace: crossplane-system
#   name: crossplane-provider-kubernetes

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   namespace: crossplane-system
#   name: crossplane-provider-kubernetes
# subjects:
# - kind: ServiceAccount
#   name: crossplane-provider-kubernetes
#   namespace: crossplane-system
# roleRef:
#   kind: ClusterRole
#   name: cluster-admin
#   apiGroup: rbac.authorization.k8s.io

# ---

# apiVersion: pkg.crossplane.io/v1alpha1
# kind: ControllerConfig
# metadata:
#   namespace: crossplane-system
#   name: crossplane-provider-kubernetes
# spec:
#   serviceAccountName: crossplane-provider-kubernetes

# ---

# apiVersion: pkg.crossplane.io/v1
# kind: Provider
# metadata:
#   namespace: crossplane-system
#   name: crossplane-provider-kubernetes
# spec:
#   package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.11.0
#   controllerConfigRef:
#     name: crossplane-provider-kubernetes
