apiVersion: azure.platformref.upbound.io/v1alpha1
kind: Cluster
metadata:
  name: platform-ref-azure-cluster
  namespace: crossplane-system
spec:
  compositeDeletePolicy: Foreground
  parameters:
    id: platform-ref-azure-cluster
    region: westus
    version: "1.27.3"
    nodes:
      count: 1
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: platform-ref-azure-cluster-kubeconfig
