---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-management
spec:
  package: xpkg.upbound.io/upbound/provider-azure-management:v0.42.1
---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  namespace: crossplane-system
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-secret
      key: creds
