apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: rgtest-2
  namespace: crossplane-system
spec:
  forProvider:
    location: West Europe
    tags:
      provisioner: crossplane
