---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  namespace: crossplane-system
  name: dot-kubernetes
spec:
  package: xpkg.upbound.io/devops-toolkit/dot-kubernetes:v0.12.29
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  namespace: a-team
  name: a-team-aks
spec:
  id: ateamaks
  compositionSelector:
    matchLabels:
      provider: azure
      cluster: aks
  parameters:
    nodeSize: small
    minNodeCount: 1
