---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  namespace: crossplane-system
  name: configuration-azure-aks
spec:
  package: xpkg.upbound.io/upbound/configuration-azure-aks:v0.3.0
---
apiVersion: azure.platform.upbound.io/v1alpha1
kind: XAKS
metadata:
  namespace: crossplane-system
  name: configuration-azure-aks
spec:
  parameters:
    id: configuration-azure-aks
    region: westus
    version: "1.28"
    nodes:
      count: 1
      instanceType: Standard_B2s
  writeConnectionSecretToRef:
    name: configuration-azure-aks-kubeconfig
    namespace: crossplane-system

