ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  labels: { }
  hosts:
    - host: crossplane.my
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: komoplane
              port:
                name: http