apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komoplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm-charts.komodor.io
    chart: komoplane
    targetRevision: 0.1.5
    helm:
      values:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          labels: { }
          hosts:
            - host: crossplane.my
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: komoplane
                      port:
                        name: http
  destination:
    server: https://kubernetes.default.svc
    namespace: komoplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamesapce=true
