apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komoplane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm-charts.komodor.io
    chart: komoplane
    targetRevision: 0.1.5
    helm:
      valueFiles:
        - komoplane-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: komoplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamesapce=true
